### PR TITLE
Include tree.pxd in source distribution

### PR DESCRIPTION
**Pull request by cgohlke**

### CODE REVIEW

**Comment by jcapriot** [comment]
Never even thought to think of what was and wasn’t included in sdist. Definitely should be pulled in.

**Comment by lheagy** [comment]
Excellent, thanks @cgohlke! I will wait until the travis test goes through and then pull this in

**Comment by jcapriot** [comment]
I think the current fail has to deal with the current non-early exit bug in the Travis script

**Comment by lheagy** [comment]
yeah, it seems to be related to #100

**Comment by lheagy** [comment]
Thanks @cgohlke! This has been included in discretize 0.3.2 which is now available on pypi: https://pypi.org/project/discretize/ (windows wheels to follow shorty)

**Pull request merged**
