### PR TITLE
Add `TreeCell.bounds` and `TreeMesh.cell_bounds` methods

### PR DESCRIPTION
**Pull request by santisoler**
**Work in progress**

Add a new `TreeCell.bounds` method that return the bounds of a cell in
a `TreeMesh`.

- Start drafting `cell_bounds` method

### CODE REVIEW

**Comment by jcapriot** [comment]
Let's add the relevant information to the underlying c++ Cell class, so you can access it easier in the `TreeMesh` as well.

**Comment by santisoler** [comment]
> Let's add the relevant information to the underlying c++ Cell class, so you can access it easier in the `TreeMesh` as well.

I agree. I would appreciate if you could help a little bit with that, or just point me in the right direction on how is the best way to do so.

**Comment by jcapriot** [comment]
Branching from #356 would be easiest, as I had put a little bit of the functionality in there already. It lets you just grab the minimum and maximum node for the c_cell pretty easily.

**Comment by jcapriot** [comment]
@santisoler this should be good now

**Review by santisoler — COMMENTED** [review]
Looks good to me. I just pushed one extra test to make sure that the bounds are returned in the right order. Feel free to merge.

**Review by jcapriot — APPROVED** [review]
LGTM, let’s merge

**Pull request merged**
