### PR TITLE
implementing bisect algorithm for searching for point indexes without…

### PR DESCRIPTION
**Pull request by jcapriot**
implementing the bisection algorithm without the GIL. Gets rid of a lot of python overhead for speed-ups. If using Cython, might as well use it to get down to C-like code.

All of the `for` loops are executed without any calls to the python interpreter, and the bisection algorithm is equivalent to the np.searchsorted without the python overhead. Also, since we know how big the `inds` and `vals` array will be, might as well pre-allocate them.

At least 2x-3x speed on decent sized arrays.

Should address #23

### CODE REVIEW

**Comment by jcapriot** [comment]
i'll fix this tonight... not quite sure why it broke tree tests though.

**Comment by rowanc1** [comment]
This looks awesome. I don't have a lot of experience with cython. Any chance you can give a brief overview tomorrow?

**Comment by jcapriot** [comment]
TreeMesh could use a lot of love to optimize it up.

**Comment by lheagy** [comment]
This looks solid @jcapriot! For an overview see https://youtu.be/zlnfQMzEOEA

**Comment by lheagy** [comment]
@rowanc1, @jcapriot: are you good with merging this??

**Comment by rowanc1** [comment]
@jcapriot can you comment?

The cython one that I made, is all yellow (python), @jcapriot wrote it so that it actually used C. 👍 

image

image

**Comment by jcapriot** [comment]
I'm good with it.
Mostly I just got around the python calls while inside the loops to make them faster!

**Pull request merged**
