### PR TITLE
Bugfix slicer

### PR DESCRIPTION
**Pull request by prisae**
Bugfix. Slicer failed if `xslice` was provided without a `yslice`, because of wrong comparison.

### CODE REVIEW

**Comment by prisae** [comment]
Thought I'd ping this one, as it is really a tiny change which is required and nothing happened for three weeks...

**Comment by prisae** [comment]
I added another bugfix to the slicer. I'd be really happy if we could move these in at some point.

**Comment by prisae** [comment]
Here graphically what this last bugfix fixes:

Before, if you provided a single value, it looked like this:
Selection_002
So the colour in the xy- and xz-plots is wrong. As soon as you scroll, the colour in the yz-plot will change to the wrong colour too.

With the bug-fix, they all get the right colour, and will remain correct if scrolling:
Selection_001

The bug only affects homogeneous fullspaces, which caused an issue with the range used by `colorbar()`.

**Comment by prisae** [comment]
Thanks for reviewing/merging. I am the one to blame introducing them in the first place...

**Comment by jcapriot** [comment]
Also means someone approved them in the first place... no worries

**Pull request merged**
