### PR TITLE
zeros_outside

### PR DESCRIPTION
**Pull request by prisae**
Calling `plot_slice` with a `TensorMesh` currently results in the following warning:

```
/path/to/conda/env/lib/python3.9/site-packages/discretize/base/base_tensor_mesh.py:785: FutureWarning: The zerosOutside keyword argument has been deprecated, please use zeros_outside. This will be removed in discretize 1.0.0
  warnings.warn(
```

This is an internal problem, and should not happen.

### CODE REVIEW

**Comment by prisae** [comment]
This started to appear in https://github.com/simpeg/discretize/commit/dcbfc4eddfaee5fa0050d42495bd83717a74164c, which is OK, basically changing the DeprecationWarning to a FutureWarning as planned.

However, when doing this we have to make sure that we do not have any internal warnings.

**Review by jcapriot — APPROVED** [review]
LGTM

**Comment by prisae** [comment]
There are potentially many other warnings that might surface, I don't know and I haven't tested! This was just the one that popped up in the emg3d-gallery...

**Comment by jcapriot** [comment]
I did a search for `zerosOutside` In the code base and this was the only spot that still had it.

**Comment by prisae** [comment]
Yes, zerosOutside should be fine. But having had a quick glance at the test logs I had the impression there were many (internal) warnings for other updated parameters. But doesn't really matter, we fix them as they surface.

**Comment by jcapriot** [comment]
Most of the tests are left alone specifically because I want them throwing the warnings to hit those lines and ensure backward compatibility. That being said I will start a `1.0.0` branch that will remove all of the pep8 conversion leftovers.

**Comment by prisae** [comment]
Fair enough.

For that I find the context manager of pytest great
```
with pytest.warns(SomeWarning...):
    do the test
```
It ensures the warning is raised, but it is not a warning in the test log, so one can aim at a zero warning tests. (You probably know all of that, just in case.)

**Pull request merged**
