### PR TITLE
Allow np.int_

### PR DESCRIPTION
**Pull request by prisae**
We should allow numpy int's in the plotting, as matplotlib handels them just fine.

We could also clean up some of the code on the way, such as `int(np.argmi(...))` could be simplified with `np.argmin()`, as it returns a `np.int_`.

Currently it simply fails (for no good reasons). -- Thoughts? (Maybe we should not check at all, and let matplotlib fail if it doesn't work, duck typing.)

### CODE REVIEW

**Comment by jcapriot** [comment]
Should we check instead for `np.integer`? That way it catches other types of integers as well, i.e. `np.int32`, `np.int8`

**Comment by prisae** [comment]
Good call, I'll change it.

Question remains, do we need to / should we check at all?

**Comment by jcapriot** [comment]
It doesn't hurt? I think the intended purpose of checking it here, is to give a slightly more customized error message than the one caused by indexing an array with a non-integer.

**Comment by prisae** [comment]
That is true. The other option would be to simply cast it `int(ind)`, but it is fine as it is. Still, including `(np.integer, int)` makes sense I think.

**Comment by prisae** [comment]
I just pushed another commit, one of the two integer checks was actually after `ind` has been used.

**Comment by jcapriot** [comment]
looks good, thanks again

**Pull request merged**
